import { getSessionById } from "@/app/actions/sessions";
import { calcTurnout } from "@/lib/computations";
import Link from "next/link";
import { notFound } from "next/navigation";
import { auth } from "@/auth";

export default async function SessionDetailPage({ params }: { params: Promise<{ id: string }> }) {
    const { id } = await params;
    const [session, sessionAuth] = await Promise.all([getSessionById(id), auth()]);
    if (!session) notFound();
    const isAdmin = sessionAuth?.user.role === "ADMIN";
    const turnout = calcTurnout(session.attendance);
    const counts = ["PRESENT", "LATE", "ABSENT", "EXCUSED"].reduce<Record<string, number>>((result, status) => ({ ...result, [status]: session.attendance.filter((record) => record.status === status).length }), {});
    const allPresent = session.attendance.length > 0 && counts.PRESENT === session.attendance.length;

    return <div>
        <Link href="/sessions" className="back-link">← Training</Link>
        <header className="compact-page-header"><div><span className="eyebrow">{session.sessionType}</span><h1>{new Date(session.sessionDate).toLocaleDateString("en-PH", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}</h1><p><strong>{session.location || "Location TBA"}</strong> · {counts.PRESENT}/{session.attendance.length} present · {Math.round(turnout * 100)}% turnout</p></div>{isAdmin && <div className="page-header-actions"><Link href={`/admin/sessions/${session.id}/edit`} className="btn btn-secondary">Edit session</Link><Link href={`/admin/sessions/${session.id}/attendance`} className="btn btn-primary">Record attendance</Link></div>}</header>
        <section className="metric-grid"><div className="metric-card accent"><span className="metric-label">Session turnout</span><strong className="metric-value">{Math.round(turnout * 100)}%</strong><div className="progress-track"><i style={{ width: `${turnout * 100}%`, background: "#fff" }} /></div></div><div className="metric-card"><span className="metric-label">Present</span><strong className="metric-value">{counts.PRESENT}</strong><span className="metric-note">athletes recorded</span></div><div className="metric-card"><span className="metric-label">Late / excused</span><strong className="metric-value">{counts.LATE} / {counts.EXCUSED}</strong><span className="metric-note">attendance exceptions</span></div><div className="metric-card"><span className="metric-label">Absent</span><strong className="metric-value">{counts.ABSENT}</strong><span className="metric-note">follow-up may be needed</span></div></section>
        <div className="grid-2" style={{ marginBottom: 18 }}><section className="surface" style={{ padding: 19 }}><span className="eyebrow">Coach coverage</span><h2 className="surface-title" style={{ marginBottom: 12 }}>Coaches present</h2>{session.coaches.length ? <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{session.coaches.map(({ coach }) => <Link href={`/coaches/${coach.id}`} className="status-chip status-upcoming" key={coach.id}>{coach.fullName}{coach.roleTitle ? ` · ${coach.roleTitle}` : ""}</Link>)}</div> : <span className="status-chip status-warning">No coach recorded</span>}</section><section className="surface" style={{ padding: 19 }}><span className="eyebrow">Training notes</span><h2 className="surface-title" style={{ marginBottom: 8 }}>Session focus</h2><p className="surface-subtitle" style={{ fontSize: 12 }}>{session.notes || "No objectives or notes were recorded for this session."}</p><p className="record-sub" style={{ marginTop: 14 }}>Last updated {session.updatedAt.toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" })}</p></section></div>
        <section className="surface"><div className="surface-header"><div><h2 className="surface-title">Attendance roster</h2><p className="surface-subtitle">{allPresent ? `All ${session.attendance.length} recorded athletes were present.` : "Review attendance status and coach notes."}</p></div><div className="page-header-actions"><span className="status-chip status-present">{counts.PRESENT} present</span>{counts.ABSENT > 0 && <span className="status-chip status-absent">{counts.ABSENT} absent</span>}</div></div>
            <div className="table-wrap" style={{ border: 0, boxShadow: "none" }}><table><thead><tr><th>Athlete</th><th>Status</th><th>Note</th><th /></tr></thead><tbody>{session.attendance.length ? session.attendance.map((record) => <tr key={record.id}><td><Link className="table-link" href={`/players/${record.player.id}`}><span className="avatar-initial">{record.player.fullName.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span>{record.player.fullName}</Link></td><td><span className={`status-chip status-${record.status.toLowerCase()}`}>{record.status.charAt(0) + record.status.slice(1).toLowerCase()}</span></td><td className="text-muted">{record.note || "—"}</td><td><Link className="row-chevron" href={`/players/${record.player.id}`}>›</Link></td></tr>) : <tr><td colSpan={4} className="empty-state" style={{ padding: 36 }}>No attendance records have been entered.</td></tr>}</tbody></table></div>
        </section>
    </div>;
}
